import { NextResponse } from "next/server";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { assertSameOrigin } from "@/lib/request-guards";
import { enforceRateLimit, RATE_LIMITS } from "@/lib/rate-limit";
import { recordAdminAction } from "@/lib/compliance/audit";

/**
 * TOTP enrolment for admin accounts — audit finding BE-4.
 *
 * Deliberately NOT behind requireAdmin({ requireMfa: true }): an admin with no
 * factor yet has to be able to reach the thing that gives them one. It is still
 * session-authenticated, so only the account holder can enrol their own factor.
 *
 * The secret is generated by Supabase and returned once, at enrolment, so it
 * never needs storing here. Verification proves the user actually loaded it
 * into an authenticator before the factor becomes usable — an unverified factor
 * grants nothing.
 */

const verifySchema = z.object({
  factorId: z.string().min(1),
  code: z.string().regex(/^\d{6}$/, "Enter the 6-digit code from your authenticator app"),
});

/** Current factors, so the settings screen can show enrolment state. */
export async function GET() {
  try {
    const supabase = await createClient();
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { data: factors } = await supabase.auth.mfa.listFactors();
    const { data: aal } = await supabase.auth.mfa.getAuthenticatorAssuranceLevel();

    return NextResponse.json(
      {
        // Only what the UI needs — never the secret or the raw factor payload.
        factors: (factors?.totp ?? []).map((f) => ({
          id: f.id,
          friendlyName: f.friendly_name,
          status: f.status,
          createdAt: f.created_at,
        })),
        currentLevel: aal?.currentLevel ?? null,
        nextLevel: aal?.nextLevel ?? null,
      },
      { status: 200 }
    );
  } catch {
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

/** Begin enrolment: returns the QR code and secret to load into an app. */
export async function POST(request: Request) {
  try {
    const csrf = assertSameOrigin(request);
    if (csrf) return csrf;
    const limited = await enforceRateLimit(request, "me:mfa", RATE_LIMITS.mfa);
    if (limited) return limited;

    const supabase = await createClient();
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { data, error } = await supabase.auth.mfa.enroll({
      factorType: "totp",
      friendlyName: `authenticator-${Date.now()}`,
    });

    if (error) {
      return NextResponse.json(
        { error: error.message || "Could not start two-factor setup" },
        { status: 400 }
      );
    }

    return NextResponse.json(
      {
        factorId: data.id,
        qrCode: data.totp.qr_code,
        secret: data.totp.secret,
        uri: data.totp.uri,
      },
      { status: 200 }
    );
  } catch {
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

/** Complete enrolment by proving possession of the secret. */
export async function PUT(request: Request) {
  try {
    const csrf = assertSameOrigin(request);
    if (csrf) return csrf;
    const limited = await enforceRateLimit(request, "me:mfa-verify", RATE_LIMITS.mfaVerify);
    if (limited) return limited;

    const supabase = await createClient();
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const parsed = verifySchema.safeParse(await request.json().catch(() => null));
    if (!parsed.success) {
      return NextResponse.json(
        { error: parsed.error.issues[0]?.message ?? "Invalid request" },
        { status: 400 }
      );
    }

    const { data: challenge, error: challengeError } =
      await supabase.auth.mfa.challenge({ factorId: parsed.data.factorId });
    if (challengeError) {
      return NextResponse.json({ error: "Could not verify that code" }, { status: 400 });
    }

    const { error: verifyError } = await supabase.auth.mfa.verify({
      factorId: parsed.data.factorId,
      challengeId: challenge.id,
      code: parsed.data.code,
    });

    if (verifyError) {
      // Generic message: a specific one distinguishes "wrong code" from
      // "expired challenge" and helps an attacker tune their guessing.
      return NextResponse.json({ error: "That code was not accepted. Try again." }, { status: 400 });
    }

    await recordAdminAction({
      actorId: user.id,
      action: "mfa.enrolled",
      targetType: "user",
      targetId: user.id,
    });

    return NextResponse.json(
      { message: "Two-factor authentication is now active on your account." },
      { status: 200 }
    );
  } catch {
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
